import type { Metadata } from "next";
import { Mansalva, Orbitron } from "next/font/google";
import "./globals.css";
import TargetCursor from "@/components/TargetCursor";
import Navbar from "@/components/layout/Navbar";
import LenisProvider from "@/components/root/LenisProvider";
import Footer from "@/components/layout/Footer";
import AuthProvider from "@/components/AuthProvider";
import { Toaster } from "react-hot-toast";

export const titleFont = Mansalva({
  weight: "400",
  subsets: ["latin"],
});

export const globalFont = Orbitron({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${globalFont.className} overflow-x-hidden`}>
      <body className="flex flex-col text-black bg-slate-100">
        <LenisProvider>
          <Toaster position="bottom-right" reverseOrder={false} />
          <TargetCursor
            spinDuration={1.4}
            hideDefaultCursor={true}
            parallaxOn
            hoverDuration={0.35}
            cursorColor="#000000"
            cursorColorOnTarget="#ff2c2c"
          />
          <AuthProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
        </LenisProvider>
      </body>
    </html>
  );
}
